// Shared team metadata — imported by the app, API routes, and share-image templates.
// `short` is an optional compact label for tight spots (both New York teams share a city).

export const NHL_TEAMS = {
  "anaheim-ducks":        { city: "Anaheim",      name: "Ducks",         abbr: "ANA", id: 24 },
  "boston-bruins":        { city: "Boston",       name: "Bruins",        abbr: "BOS", id: 6  },
  "buffalo-sabres":       { city: "Buffalo",      name: "Sabres",        abbr: "BUF", id: 7  },
  "calgary-flames":       { city: "Calgary",      name: "Flames",        abbr: "CGY", id: 20 },
  "carolina-hurricanes":  { city: "Carolina",     name: "Hurricanes",    abbr: "CAR", id: 12 },
  "chicago-blackhawks":   { city: "Chicago",      name: "Blackhawks",    abbr: "CHI", id: 16 },
  "colorado-avalanche":   { city: "Colorado",     name: "Avalanche",     abbr: "COL", id: 21 },
  "columbus-blue-jackets":{ city: "Columbus",     name: "Blue Jackets",  abbr: "CBJ", id: 29 },
  "dallas-stars":         { city: "Dallas",       name: "Stars",         abbr: "DAL", id: 25 },
  "detroit-red-wings":    { city: "Detroit",      name: "Red Wings",     abbr: "DET", id: 17 },
  "edmonton-oilers":      { city: "Edmonton",     name: "Oilers",        abbr: "EDM", id: 22 },
  "florida-panthers":     { city: "Florida",      name: "Panthers",      abbr: "FLA", id: 13 },
  "los-angeles-kings":    { city: "Los Angeles",  name: "Kings",         abbr: "LAK", id: 26 },
  "minnesota-wild":       { city: "Minnesota",    name: "Wild",          abbr: "MIN", id: 30 },
  "montreal-canadiens":   { city: "Montréal",     name: "Canadiens",     abbr: "MTL", id: 8  },
  "nashville-predators":  { city: "Nashville",    name: "Predators",     abbr: "NSH", id: 18 },
  "new-jersey-devils":    { city: "New Jersey",   name: "Devils",        abbr: "NJD", id: 1  },
  "new-york-islanders":   { city: "New York",     name: "Islanders",     abbr: "NYI", id: 2,  short: "NY Isles"   },
  "new-york-rangers":     { city: "New York",     name: "Rangers",       abbr: "NYR", id: 3,  short: "NY Rangers" },
  "ottawa-senators":      { city: "Ottawa",       name: "Senators",      abbr: "OTT", id: 9  },
  "philadelphia-flyers":  { city: "Philadelphia", name: "Flyers",        abbr: "PHI", id: 4  },
  "pittsburgh-penguins":  { city: "Pittsburgh",   name: "Penguins",      abbr: "PIT", id: 5  },
  "san-jose-sharks":      { city: "San Jose",     name: "Sharks",        abbr: "SJS", id: 28 },
  "seattle-kraken":       { city: "Seattle",      name: "Kraken",        abbr: "SEA", id: 55 },
  "st-louis-blues":       { city: "St. Louis",    name: "Blues",         abbr: "STL", id: 19 },
  "tampa-bay-lightning":  { city: "Tampa Bay",    name: "Lightning",     abbr: "TBL", id: 14 },
  "toronto-maple-leafs":  { city: "Toronto",      name: "Maple Leafs",   abbr: "TOR", id: 10 },
  "utah-mammoth":         { city: "Utah",         name: "Mammoth",       abbr: "UTA", id: 59 },
  "vancouver-canucks":    { city: "Vancouver",    name: "Canucks",       abbr: "VAN", id: 23 },
  "vegas-golden-knights": { city: "Vegas",        name: "Golden Knights",abbr: "VGK", id: 54 },
  "washington-capitals":  { city: "Washington",   name: "Capitals",      abbr: "WSH", id: 15 },
  "winnipeg-jets":        { city: "Winnipeg",     name: "Jets",          abbr: "WPG", id: 52 },
};


// Primary brand colour per team (by abbreviation). Dark navies are lightened in CSS for dark mode.
export const TEAM_COLORS = {
  ANA: "#F47A38",
  BOS: "#FFB81C",
  BUF: "#003087",
  CGY: "#C8102E",
  CAR: "#CE1126",
  CHI: "#CF0A2C",
  COL: "#6F263D",
  CBJ: "#002654",
  DAL: "#006847",
  DET: "#CE1126",
  EDM: "#FF4C00",
  FLA: "#C8102E",
  LAK: "#A2AAAD",
  MIN: "#154734",
  MTL: "#AF1E2D",
  NSH: "#FFB81C",
  NJD: "#CE1126",
  NYI: "#00539B",
  NYR: "#0038A8",
  OTT: "#C52032",
  PHI: "#F74902",
  PIT: "#FCB514",
  SJS: "#006D75",
  SEA: "#99D9D9",
  STL: "#002F87",
  TBL: "#002868",
  TOR: "#00205B",
  UTA: "#69B3E7",
  VAN: "#00205B",
  VGK: "#B4975A",
  WSH: "#C8102E",
  WPG: "#041E42",
};
